title: Alisha Sarfani
logo: /assets/img/Alisha.logo.png
description: Aspiring Data Analyst | MS Applied Analytics | Saint Louis University | Research Development Intern | Graduate Assistant
show_downloads: true
theme: jekyll-theme-minimal
